### PR TITLE
added jdk21 to test matrix

### PR DESCRIPTION
**Pull request by judovana**
This is adding jdk21 to jdk test matrix and removing at8 branch, which is no longer used
I had not added at7 branch.
---------
### Progress
- [x] Change must not contain extraneous whitespace

### Error
&nbsp;⚠️ The pull request body must not be empty.

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/asmtools.git pull/72/head:pull/72` \
`$ git checkout pull/72`

Update a local copy of the PR: \
`$ git checkout pull/72` \
`$ git pull https://git.openjdk.org/asmtools.git pull/72/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 72`

View PR using the GUI difftool: \
`$ git pr show -t 72`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/asmtools/pull/72.diff">https://git.openjdk.org/asmtools/pull/72.diff</a>

</details>

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/asmtools.git pull/72/head:pull/72` \
`$ git checkout pull/72`

Update a local copy of the PR: \
`$ git checkout pull/72` \
`$ git pull https://git.openjdk.org/asmtools.git pull/72/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 72`

View PR using the GUI difftool: \
`$ git pr show -t 72`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/asmtools/pull/72.diff">https://git.openjdk.org/asmtools/pull/72.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/asmtools/pull/72#issuecomment-1898533209)

### CODE REVIEW

**Comment by judovana** [comment]
waiting for gh actions to prove itslef

**Comment by judovana** [comment]
hm. I think the gh actions do nto work as expected, that they are overridden by openjdk project.

**Comment by judovana** [comment]
@lkuskov afik this PR is ok. IDK why the GH do not run here. In my fork, it run correctly under  jdk21

**Comment by lkuskov** [comment]
LGTM! Please integrate

**Pull request closed without merging**
