### PR TITLE
Javadoc and sources

### PR DESCRIPTION
**Pull request by judovana**
To proceed with release to maven repositories, source and javadoc jars are mandatory. Thus adding the,

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/asmtools pull/19/head:pull/19` \
`$ git checkout pull/19`

Update a local copy of the PR: \
`$ git checkout pull/19` \
`$ git pull https://git.openjdk.java.net/asmtools pull/19/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19`

View PR using the GUI difftool: \
`$ git pr show -t 19`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/asmtools/pull/19.diff">https://git.openjdk.java.net/asmtools/pull/19.diff</a>

</details>

### CODE REVIEW

**Comment by judovana** [comment]
I do not lihe last commit, but the new naming resulting to 
```
repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea.jar
repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea.pom
repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea-javadoc.jar
repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea-sources.jar
```
is more like the other members of eg: https://repo1.maven.org/maven2/org/openjdk/

**Comment by lkuskov** [comment]
Looks good. There is just one comment: do we need the suffix "core" for tagging asmtools jars. Actually asmtools doesn't have plugins, extra libraries or something else to emphasize meaning of core API.

**Comment by judovana** [comment]
Thank you very much for bringing it up, as - to be honest - I really do not have clear preference.  Afaik, the initial group of org.openjdk and artifact asmtools, was the most correct one. But as OpenJDK is huge, and consists not only from subprojects, but also from subbgroups org.openjdk.{jmh,nashorn,...,asmtools} gave somehow sense too. That lead to artifact of asmtools in group org.openjkd.asmtools - which is terrible.  Looking to the above m2 repo, then org.openjdk.project + project-something, where each, even singlelibray one (eg: https://repo1.maven.org/maven2/org/openjdk/nashorn/ ) have the core suffix.  Thus, the org.openjdk.asmtools with artifact asmtools-core, sounded most aligned and more extensible and more readable and more clear on first sight then just artifact of asmtools.

However, I will follow your knowledge. I agree with all three names:
 * org.openjkd+asmtools
 * org.openjkd.asmtools+asmtools
 * org.openjkd.asmtools+asmtools-core

But asmtools shouldl follow the schema of  other openjdk projects in maven repo.

**Comment by lkuskov** [comment]
Thank you for the explanation - sounds reasonable. Please integrate this variant: 
repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea.jar
repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea.pom
repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea-javadoc.jar
repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea-sources.jar

**Comment by judovana** [comment]
Youp, that is current implementation. Will I integrate then?

**Comment by judovana** [comment]
```
[INFO] --- maven-install-plugin:2.4:install (default-install) @ asmtools-core ---
[INFO] Installing /home/jvanek/git/asmtools/maven/target/asmtools-core-7.0.b10-ea.jar to /home/jvanek/.m2/repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea.jar
[INFO] Installing /home/jvanek/git/asmtools/maven/pom.xml to /home/jvanek/.m2/repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea.pom
[INFO] Installing /home/jvanek/git/asmtools/maven/target/asmtools-core-7.0.b10-ea-javadoc.jar to /home/jvanek/.m2/repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea-javadoc.jar
[INFO] Installing /home/jvanek/git/asmtools/maven/target/asmtools-core-7.0.b10-ea-sources.jar to /home/jvanek/.m2/repository/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea-sources.jar
```

**Pull request closed without merging**
