### PR TITLE
replace stdout by configurable object

### PR DESCRIPTION
**Pull request by judovana**
See https://github.com/openjdk/asmtools/pull/38 for full story
The PR will be enhanced by handling of two streams in compiler logger. Then the stdout work can continue.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/asmtools pull/44/head:pull/44` \
`$ git checkout pull/44`

Update a local copy of the PR: \
`$ git checkout pull/44` \
`$ git pull https://git.openjdk.org/asmtools pull/44/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 44`

View PR using the GUI difftool: \
`$ git pr show -t 44`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/asmtools/pull/44.diff">https://git.openjdk.org/asmtools/pull/44.diff</a>

</details>

### CODE REVIEW

**Comment by lkuskov** [comment]
I ain't sure that all these files should be integrated. At least class files that reveal the problem with initialized String fields should be excluded from integration.

**Comment by judovana** [comment]
This is WIP - work in progress. It ave to be finished first.

**Comment by judovana** [comment]
Hi Leonid!
Can you take an eye?  My next steps will be to add switch to jcod/jasm so they will use the original dual stream logging or not. Then I will add the stdout capability to jasm/jcod and will turn the dual stream logger off by default.
Last step may be to remove the dual stream logging. And that is the question on you. If you wish to keep the dual stream logging for compilers as optional, then - by current impl, the nasty prints/printe methods will remain. If you will be rather happy to remove dual stream logging completely, then the nasty prints/printe wil lbe gone. Actually whole unhappy DualStreamLogger will be gone, which sounds tempting.

I'm in favour of dropping it and log to stderr only, but it may break older consummers... so Most likley lets keep it optional, and remove in some far future?

**Comment by lkuskov** [comment]
Hi, your changes look good.
#My next steps will be to add switch to jcod/jasm so they will use the original dual stream logging or not. Then I will add the stdout capability to jasm/jcod and will turn the dual stream logger off by default.
Once your dual logging is implemented I will verify using the new version of asmtools against harnesses to check it doesn't break functionality. if everything is OK you will cut off dual streaming.

**Comment by judovana** [comment]
great. ty!

**Comment by lkuskov** [comment]
> Is it ok for you to start playing with it?
Yes, it is. I'm going to start testing this week. 
Thank you

**Comment by judovana** [comment]
Hello!

I had chaged dual stream logging  to stderr only. You can turn back to original behavior by -dls switch
From point of view of streams, it indeed do not have sense. Looking forward too get rid of it.

Hopefully all yours tests will pass!

**Comment by judovana** [comment]
I had rellised adding the -dsl switch for disassemblers is nonsense.. But I guess it do not metter fot his case,

**Comment by judovana** [comment]
Hello!

This is final logical commit on this topic. if you do not like the changes now, I will be very very sad :)
i think the commit is speaking for itself, how nicely is now j(dis)asm and j(de)coder  reusable in libraries.
For non-logical commits I have in mind 
 - refactor ToolsInput/Output interfaces with many inner classes to separate pkg
 - adjust readme.md which will describe library-like usage
 - if you would agree, then  rename four Main classes to match what they are Main of eg jasm.Main -> jasm.JasmMain - it is super easy to call wrong main.

**Comment by judovana** [comment]
Jsut an idea.. shouldnt:
```
public static class TextOutput extends NamedToolOutput {
        private final ArrayList<NamedSource> outputs = new ArrayList<>();
        private StringBuilder currentClass;
```
use  `uEscWriter` as `currentClass` wrapper?? I tried both, but ahve nto spotted difference, so used sting directly

**Comment by lkuskov** [comment]
I like your updates, everything looks good. I've checked your changes they didn't cause any regression in what I was able to test.   

> refactor ToolsInput/Output interfaces with many inner classes to separate pkg

`Agreed`

> adjust readme.md which will describe library-like usage

:+1:

>if you would agree, then rename four Main classes to match what they are Main of eg jasm.Main -> jasm.JasmMain - it is super easy to call wrong main.

`Doesn't work - there are  few references that can't be updated`

>get rid of dual stream logging? Now when I see the intnetional usage between trace/log maybe it canbe usefull to keep it in. But on the other side, it is confusing.

`Let's keep it in`

> use uEscWriter as currentClass wrapper??

Much better to use uEscWriter

Concerning my changes - I've added couple new methods into Main classes to keep asmtools working with some old staff. And right now I'm fixing constructions like this one that jasm is losing during decoding:
`
 0:    ldc               #1;            // Dynamic REF_invokeStatic:Method cpldyn00105m013.method20:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":
                                            // name:"I" {
                                            //   Dynamic REF_invokeStatic:Method cpldyn00105m013.method19:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //     Dynamic REF_invokeStatic:Method cpldyn00105m013.method18:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //       Dynamic REF_invokeStatic:Method cpldyn00105m013.method17:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //         Dynamic REF_invokeStatic:Method cpldyn00105m013.method16:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //           Dynamic REF_invokeStatic:Method cpldyn00105m013.method15:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //             Dynamic REF_invokeStatic:Method cpldyn00105m013.method14:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //               Dynamic REF_invokeStatic:Method cpldyn00105m013.method13:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                 Dynamic REF_invokeStatic:Method cpldyn00105m013.method12:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                   Dynamic REF_invokeStatic:Method cpldyn00105m013.method11:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                     Dynamic REF_invokeStatic:Method cpldyn00105m013.method10:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                       Dynamic REF_invokeStatic:Method cpldyn00105m013.method9:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                         Dynamic REF_invokeStatic:Method cpldyn00105m013.method8:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                           Dynamic REF_invokeStatic:Method cpldyn00105m013.method7:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                             Dynamic REF_invokeStatic:Method cpldyn00105m013.method6:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                               Dynamic REF_invokeStatic:Method cpldyn00105m013.method5:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                                 Dynamic REF_invokeStatic:Method cpldyn00105m013.method4:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                                   Dynamic REF_invokeStatic:Method cpldyn00105m013.method3:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                                     Dynamic REF_invokeStatic:Method cpldyn00105m013.method2:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                                       Dynamic REF_invokeStatic:Method cpldyn00105m013.method1:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                                         Dynamic REF_invokeStatic:Method cpldyn00105m013.method20:"(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I":name:"I" {
                                            //                                           String "foo-bar"
                                            //                                         }
                                            //                                       }
                                            //                                     }
                                            //                                   }
                                            //                                 }
                                            //                               }
                                            //                             }
                                            //                           }
                                            //                         }
                                            //                       }
                                            //                     }
                                            //                   }
                                            //                 }
                                            //               }
                                            //             }
                                            //           }
                                            //         }
                                            //       }
                                            //     }
                                            //   }
                                            // }
`

**Comment by judovana** [comment]
tyvm for update!

**Pull request merged**
