### PR TITLE
Revert 33 revert 32 stdin

### PR DESCRIPTION
**Pull request by lkuskov**
After merging and testing I've found the following issue that I've missed before. 
If I call jasm -version I will stuck with 
>asm -version
 Java Assembler Tools, version 8.0 ea 02 (August 23, 2022). 

I.e. there is no sign that the tool is waiting for stdin. 

From my point of view there is the good vim solution: 
Usage: vim [arguments] [file ..]       edit specified file(s)
              or: vim [arguments] -          read text from stdin

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/asmtools pull/34/head:pull/34` \
`$ git checkout pull/34`

Update a local copy of the PR: \
`$ git checkout pull/34` \
`$ git pull https://git.openjdk.org/asmtools pull/34/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 34`

View PR using the GUI difftool: \
`$ git pr show -t 34`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/asmtools/pull/34.diff">https://git.openjdk.org/asmtools/pull/34.diff</a>

</details>

### CODE REVIEW

**Comment by lkuskov** [comment]
Also this problem will arise each time any flag without file is used.

**Comment by lkuskov** [comment]
it will be much better to simply add one more PR. Sorry for disturbing

**Comment by judovana** [comment]
The -version should not be stuck under all cases. I see the error i my code. Will fix.
As for the "-" for std in, I do not have strong preference. I usually prefer  direct stdin unless said otherwise, but it have its issues.

**Comment by judovana** [comment]
Isn't worthy to touch the master, and remove the revert and revert of revert?

**Pull request closed without merging**
