### PR TITLE
Unstuck version

### PR DESCRIPTION
**Pull request by judovana**
Hello! This pr is solving - and is not - the hanged waiting for stdin for no file argument.
1) it properly exits after version is printed, thus is unaffected by any file arguments (and streams) which may change alter
2) it changes the Stream (and extending) input implemetation to lazily drain the stream once needed, not durign construction. TBH, I'm not sure with this change, but I was generally very unhappy  by draining the stream in cosntructor at all. This alone, would not solve the -version problem, because the StreamInput is added always, and thus is always processed, thus stdin is read no meter if it is lazy or in constructor.

This intentionally do not add the empty "-" switch. That may come later as needed.

Hints welcomed!

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/asmtools pull/36/head:pull/36` \
`$ git checkout pull/36`

Update a local copy of the PR: \
`$ git checkout pull/36` \
`$ git pull https://git.openjdk.org/asmtools pull/36/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 36`

View PR using the GUI difftool: \
`$ git pr show -t 36`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/asmtools/pull/36.diff">https://git.openjdk.org/asmtools/pull/36.diff</a>

</details>

### CODE REVIEW

**Comment by judovana** [comment]
Note, that (2) is good also for usecase, when `ArrayList<ToolInput> fileList` can now get setters/getters, and thus allow usage of the code as library. I wanted to do this via constructor, which would set the `ArrayList<ToolInput> fileList` or by this lazy approach and setter/getter on `ArrayList<ToolInput> fileList` - which is more versatile.

**Comment by judovana** [comment]
hmmm. Ihad noted, that stdin and file inputs, when jasm or jcoder are called  with invalid input, prints different errors.  file one prints just "ERROR: Cannot read" (+ exception in verbose mode), but in case of stdin individual parsing errors are printed. Am not sure which one is correct

**Comment by lkuskov** [comment]
There should be unified notification mechanism. It would be good to have the same format of messages for all input/output streams. "ERROR: Cannot read" (+ exception in verbose mode)

**Comment by judovana** [comment]
By the quick glance I have not found it. I definitely agree that the unified  cant read should be there + trace  in verbose.. and  with al the nice diagnostic syntax errors when I say "pretty please" :)
Those should go to the the stderr by default, and shoudl be there. And should be configurable by the same mechanism as I do the stdin/out. I'm pretty sure I wil hit it several time and fix it on longer run.

Can this PR be merged please?

**Pull request closed without merging**
