### PR TITLE
Created maven binding to make easy maven integration

### PR DESCRIPTION
**Pull request by judovana**
Simplest maven wrapper without any duplicated code (with hardcoded version) to allow simple  asmtools usage via maven depndencies. The namespace (org.openjdk) is same as for JMH

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Error
&nbsp;⚠️ Symbolic links are not allowed (file: maven/src/main/resources/org/openjdk/asmtools/util/productinfo.properties)

### Download
`$ git fetch https://git.openjdk.java.net/asmtools pull/13/head:pull/13`
`$ git checkout pull/13`

### CODE REVIEW

**Comment by judovana** [comment]
https://bugs.openjdk.java.net/browse/SKARA-854

**Comment by robilad** [comment]
Hi, can you send me an e-mail at Dalibor.Topic@oracle.com so that I can mark your account as verified?

**Comment by judovana** [comment]
done. TY!

**Comment by judovana** [comment]
ping please?

**Comment by lkuskov** [comment]
Hi Judovana! Two fixes that flush outputs look good. The maven support is reasonable. Does it need to have the resource productinfo.properties there?  Please fix the failed check. Once it's done I will integrate your fixes. Sorry for the long delay I was inactive these weeks.

**Comment by judovana** [comment]
Hi Leonid!
Thank you very much for review. 
I will split it to two - to flushes and to maven binding. As there can be issue with the maven binding
You can see, that jcheck failed with "Symbolic links are not allowed (file: maven/src/main/resources/org/openjdk/asmtools/util/productinfo.properties)". Where productinfo.properties is probably not important the test ishsowing just tip of the iceberg - the maven binding,  relayes on symlinks.
I'm aware it is then linux only, but that why I set "unsupported maven wrapper.." into description.
If the symlinks are really no-go, then I would probably repalce the pom.xml by shell script, screting symlinks and pom on the fly. That can be later extended with batch file, which will copy the files instead of linking.
Small advantage is, that in this case I can read the version from build/productinfo.properties
What is your preference?

**Comment by judovana** [comment]
Split:
https://github.com/openjdk/asmtools/pull/15
https://github.com/openjdk/asmtools/pull/16

I would recommend to continue discussion in here. Sorry for not splitting earlier.

**Pull request closed without merging**
