### PR TITLE
Added gpg plugin and steps for release

### PR DESCRIPTION
**Pull request by judovana**
Usually the maven release plugin or gpg release plugin are working with direct access to repo - push change of versions, tag, do release, and again bump versions for next development cycle. As for asmtools, the maven is just secondary, unsupported release medium so I had opted for upload of locally finished binaries. Thus the manual ```mvn clean verify gpg:sign install:install deploy:deploy -DaltDeploymentRepository=ossrh::default::https://oss.sonatype.org/service/local/staging/deploy/maven2/ ```  command in pom comment. 
This may not be best, but for now it is the only way I found to upload locally created binaries. But I must admit, I'm not 100% sure in maven reelase or gpg plugins. During the next releases, maybe I will find something better.

As the PR is now, the asmtools artifacts are uploaded in staging maven central: https://oss.sonatype.org/content/repositories/orgopenjdkasmtools-1002/org/openjdk/asmtools/asmtools-core/

I had tested it and it works as expected (https://github.com/pmikova/java-runtime-decompiler/commit/d8b5a03759b9e8dfe584b0052778ff590ba6e82b).

One offtopic question  - the {slash}integrate and/or {slash}sponsor is autoamtically squashing commits?

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/asmtools pull/20/head:pull/20` \
`$ git checkout pull/20`

Update a local copy of the PR: \
`$ git checkout pull/20` \
`$ git pull https://git.openjdk.java.net/asmtools pull/20/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20`

View PR using the GUI difftool: \
`$ git pr show -t 20`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/asmtools/pull/20.diff">https://git.openjdk.java.net/asmtools/pull/20.diff</a>

</details>

### CODE REVIEW

**Comment by judovana** [comment]
I will move from staging to maven central once this PR is merged.

**Comment by lkuskov** [comment]
Looks good. I'll be a sponsor for your integration. The OpenJDK repos were initialized with options: 
Setting Options: Merge button → Only allow squash merging
Settings General Merge Request: Squash commits when merging → Encourage

**Comment by judovana** [comment]
TY!

here we go:
https://repo1.maven.org/maven2/org/openjdk/asmtools/asmtools-core/
https://oss.sonatype.org/#nexus-search;quick~asmtools
To bubble to: https://mvnrepository.com/artifact/org.openjdk will take few hours, mayube days.  But the artifact is already usable. 

Thanx  for support!

**Comment by lkuskov** [comment]
Great news!
Thank you,
Leonid

From: judovana ***@***.***>
Reply-To: openjdk/asmtools ***@***.***>
Date: Friday, June 11, 2021 at 2:07 AM
To: openjdk/asmtools ***@***.***>
Cc: Leonid Kuskov ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [openjdk/asmtools] Added gpg plugin and steps for release (#20)


TY!

here we go:
https://repo1.maven.org/maven2/org/openjdk/asmtools/asmtools-core/<https://urldefense.com/v3/__https:/repo1.maven.org/maven2/org/openjdk/asmtools/asmtools-core/__;!!GqivPVa7Brio!LYIrV2RfIJd8gm2l0WRYsgpPO4lZ-3M_134ZF4K7Qt9MeM9i7NrnaAlaNpkFqIJLtcQ$>
https://oss.sonatype.org/#nexus-search;quick~asmtools<https://urldefense.com/v3/__https:/oss.sonatype.org/*nexus-search;quick*asmtools__;I34!!GqivPVa7Brio!LYIrV2RfIJd8gm2l0WRYsgpPO4lZ-3M_134ZF4K7Qt9MeM9i7NrnaAlaNpkFwaOH4HQ$>
To bubble to: https://mvnrepository.com/artifact/org.openjdk<https://urldefense.com/v3/__https:/mvnrepository.com/artifact/org.openjdk__;!!GqivPVa7Brio!LYIrV2RfIJd8gm2l0WRYsgpPO4lZ-3M_134ZF4K7Qt9MeM9i7NrnaAlaNpkFZqqHMR0$> will take few hours, mayube days. But the artifact is already usable.

Thanx for support!

**Pull request closed without merging**
