### PR TITLE
made maven resource plugin and  (un)setDetailedOutputOptions expclicit

### PR DESCRIPTION
**Pull request by judovana**
That is still sufferign the https://issues.apache.org/jira/browse/MRESOURCES-237 so the filtering was done. Fitlering is excluding proeprties (as they claim they are ascii) and is adding .class sufix for test classes.  Another solution is to use mrp 2.6 which do not suffer the symlinks issue

In both cases, the tests still fail in maven runs, although rummor is, manually it passes (todo, verify)

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/asmtools.git pull/68/head:pull/68` \
`$ git checkout pull/68`

Update a local copy of the PR: \
`$ git checkout pull/68` \
`$ git pull https://git.openjdk.org/asmtools.git pull/68/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 68`

View PR using the GUI difftool: \
`$ git pr show -t 68`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/asmtools/pull/68.diff">https://git.openjdk.org/asmtools/pull/68.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/asmtools/pull/68#issuecomment-1812392197)

### CODE REVIEW

**Comment by judovana** [comment]
Please, do not merge yet.
The PR exists onlyh to let you know tham I'm (although terribly rarely) on the issue with maven bindings and resources.


Currently I would like to discuss a direction of this PR:
  - to move to maven-resources-plugin 2.6 and then the issue will be indeed gone
  - to stay on 3.x with filtering, as shown in this PR

AFAICT, to stay on 3.x is the only viable solution for future. if we agree on that, we can merge, because at least there is explicit maven plugin version.


However the filtered resources did not had the expected results. I need to dive into it one more times

**Comment by lkuskov** [comment]
The second direction seems more preferable. Since there is no rush, it makes sense to integrate a comprehensive fix for this Maven-Git issue. Thank you very much.

**Comment by judovana** [comment]
ok. ty!

**Comment by judovana** [comment]
So the first test-failure was passing in ide and not from cmdline, becasue it was order sensitive.

The Options.(un)setDetailedOutputOptions and its underlying  static private EnumSet<PR> printOptions = JASM; are unlucily static fields, co currently shared over environment, so in world of tests very dangerous.

To move them out of static scope shoud be separate from this PR (if ever)


While doing this, I had removed the reflexive wrapper. it was literally duplicated code  with already existing methods which were based on simple if in two values. The usage of refelction without proper apis made no sense to me, and was making adaptation to (un) setDetailedOutputOptions harder (as it was just Object). i had chosen to remove it instead of casting the output.

If you insists on proper reflexion-based solution, I would be happy to do so.  It will howevere requrire some more interfaces like Compilable, Decompilable and/or Mainable (weird, but serve its purpose). 

There is still one failing test. Am on it. Sorry for delay, and happy new year to whole jasmtools team.

**Comment by judovana** [comment]
One more test was broken by removal of the reflexive wrappers.  IIU the test correclty checking returns from the main calls should be enough. Can you double check  the [1d68964](https://github.com/openjdk/asmtools/pull/68/commits/1d68964fe729723291e891eb1d9a92171c0f4e00) commit please?

**Comment by judovana** [comment]
```
[ERROR] Failures: 
[ERROR]   JdisJasmTest.jdisJasmAllDecompileCompileAndLoad:35 from 312 failed to assemble  to (/tmp/JdisJasmWorks11256963108958081796) 4: /org/openjdk/asmtools/jasm/Parser.class, /org/openjdk/asmtools/jasm/ClassData.class, /org/openjdk/asmtools/jasm/ClassData$CoreClasses.class, /org/openjdk/asmtools/jasm/ParserCP$ParserCPVisitor.class ==> expected: <0> but was: <4>
[INFO] 
[ERROR] Tests run: 42, Failures: 1, Errors: 0, Skipped: 0

```

This  fails also from  ide.  those are the two testes which disasm+jasm all classes in asmtools. I had not double chack if it is tstsuite fail or not
```
failed to assemble  to (/tmp/JdisJasmWorks4524501601177207005) 4:
  /org/openjdk/asmtools/jasm/Parser.class,
  /org/openjdk/asmtools/jasm/ClassData.class,
   /org/openjdk/asmtools/jasm/ClassData$CoreClasses.class,
   /org/openjdk/asmtools/jasm/ParserCP$ParserCPVisitor.class ==> 
Expected :0
Actual   :4
```

```
JdisJasmWorks17221649995522723990.java (30:16) Error: Either name or Constant Pool index expected, got "<this_class> [85]"
  public Method this_class:"(Lorg/openjdk/asmtools/jasm/ClassData$CoreClasses$PLACE;Lorg/openjdk/asmtools/jasm/ConstCell;)V":"(Lorg/openjdk/asmtools/jasm/ClassData$CoreClasses$PLACE;Lorg/openjdk/asmtools/jasm/ConstCell<*>;)V" 
                ^
JdisJasmWorks17221649995522723990.java (49:16) Error: Either name or Constant Pool index expected, got "<super_class> [86]"
  public Method super_class:"(Lorg/openjdk/asmtools/jasm/ClassData$CoreClasses$PLACE;Lorg/openjdk/asmtools/jasm/ConstCell;)V":"(Lorg/openjdk/asmtools/jasm/ClassData$CoreClasses$PLACE;Lorg/openjdk/asmtools/jasm/ConstCell<*>;)V" 
                ^
JdisJasmWorks17221649995522723990.java (68:16) Error: Either name or Constant Pool index expected, got "<this_class> [85]"
  public Method this_class:"(Lorg/openjdk/asmtools/jasm/ConstCell;)V":"(Lorg/openjdk/asmtools/jasm/ConstCell<*>;)V" 
                ^
JdisJasmWorks17221649995522723990.java (88:16) Error: Either name or Constant Pool index expected, got "<super_class> [86]"
  public Method super_class:"(Lorg/openjdk/asmtools/jasm/ConstCell;)V":"(Lorg/openjdk/asmtools/jasm/ConstCell<*>;)V" 
                ^
JdisJasmWorks17221649995522723990.java (108:16) Error: Either name or Constant Pool index expected, got "<this_class> [85]"
  public Method this_class:"()Lorg/openjdk/asmtools/jasm/ConstCell;":"()Lorg/openjdk/asmtools/jasm/ConstCell<*>;" 
                ^
JdisJasmWorks17221649995522723990.java (129:16) Error: Either name or Constant Pool index expected, got "<super_class> [86]"
  public Method super_class:"()Lorg/openjdk/asmtools/jasm/ConstCell;":"()Lorg/openjdk/asmtools/jasm/ConstCell<*>;" 
                ^
6 error(s)
JdisJasmWorks14220440161711403130.java (93:56) Error: Either name or Constant Pool index expected, got "<this_class> [85]"
         invokevirtual     Method ClassData$CoreClasses.this_class:"(Lorg/openjdk/asmtools/jasm/ClassData$CoreClasses$PLACE;Lorg/openjdk/asmtools/jasm/ConstCell;)V";
                                                        ^
1 error(s)
JdisJasmWorks7075826855074029768.java (6840:56) Error: Either name or Constant Pool index expected, got "<super_class> [86]"
         invokevirtual     Method ClassData$CoreClasses.super_class:"(Lorg/openjdk/asmtools/jasm/ClassData$CoreClasses$PLACE;Lorg/openjdk/asmtools/jasm/ConstCell;)V";
                                                        ^
1 error(s)
JdisJasmWorks7929375517498511475.java (943:56) Error: Either name or Constant Pool index expected, got "<this_class> [85]"
         invokevirtual     Method ClassData$CoreClasses.this_class:"()Lorg/openjdk/asmtools/jasm/ConstCell;";
                                                        ^
1 error(s)
/home/jvanek/git/asmtools/maven/target/classes/org/openjdk/asmtools/jasm/ClassData$CoreClasses.class
```

**Comment by lkuskov** [comment]
Happy New Year!
Thank you for letting me know about this. These six errors are a regression caused by adding support for 'this_class/super_class' entries. Once I have a fix, I will check the commit - 1d68964.

**Comment by judovana** [comment]
Oh I see. thanx a lot!

**Comment by lkuskov** [comment]
I've fixed the 'this_class/super_class' issue [7903620](https://bugs.openjdk.org/browse/CODETOOLS-7903620) and tested your commit [1d68964](https://github.com/openjdk/asmtools/commit/1d68964fe729723291e891eb1d9a92171c0f4e00). Everything works in IDE, and all tests have passed. However, to achieve this, I copied all i18n.properties files to the directory maven/target/classes to replace missing links.

**Comment by judovana** [comment]
thanx for quick fix! I had rebased on top if it, and now all tests via `mvn clean test`  are indeed passing without any maual copying. So it seems we are done here.

```
 jvanek  jvanek  11:15:18  ~  git  asmtools  maven  exactRessourcePlugin  $  sh mvngen.sh 
Generating /home/jvanek/git/asmtools/maven/pom.xml for asmtools 8.0 ea 10 (Java Assembler Tools)
Done
Creating symlinks to symulate maven structure
Done
 jvanek  jvanek  11:15:26  ~  git  asmtools  maven  exactRessourcePlugin  $  JAVA_HOME=/usr/lib/jvm/java-17-openjdk mvn clean test
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< org.openjdk:asmtools >------------------------
[INFO] Building asmtools 8.0.b10-ea
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ asmtools ---
[INFO] Deleting /home/jvanek/git/asmtools/maven/target
[INFO] 
[INFO] --- maven-resources-plugin:3.3.1:resources (default-resources) @ asmtools ---
[INFO] Copying 6 resources from src/main/resources to target/classes
[INFO] Copying 42 resources from src/test/resources to target/classes
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ asmtools ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 150 source files to /home/jvanek/git/asmtools/maven/target/classes
[INFO] /home/jvanek/git/asmtools/maven/src/main/java/org/openjdk/asmtools/jdis/MemberData.java: Some input files use unchecked or unsafe operations.
[INFO] /home/jvanek/git/asmtools/maven/src/main/java/org/openjdk/asmtools/jdis/MemberData.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:3.3.1:testResources (default-testResources) @ asmtools ---
[INFO] Copying 42 resources from src/test/resources to target/test-classes
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ asmtools ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 46 source files to /home/jvanek/git/asmtools/maven/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M9:test (default-test) @ asmtools ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openjdk.asmtools.jcoder.MultipleFilesInSingleJcoderTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.09 s - in org.openjdk.asmtools.jcoder.MultipleFilesInSingleJcoderTest
[INFO] Running org.openjdk.asmtools.InputOutputTests
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.22 s - in org.openjdk.asmtools.InputOutputTests
[INFO] Running org.openjdk.asmtools.jdec.MainTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.061 s - in org.openjdk.asmtools.jdec.MainTest
[INFO] Running org.openjdk.asmtools.jdec.JdecJcodTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.529 s - in org.openjdk.asmtools.jdec.JdecJcodTest
[INFO] Running org.openjdk.asmtools.transform.case7903259Tests
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 s - in org.openjdk.asmtools.transform.case7903259Tests
[INFO] Running org.openjdk.asmtools.transform.case7903454Tests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.083 s - in org.openjdk.asmtools.transform.case7903454Tests
[INFO] Running org.openjdk.asmtools.transform.case8302260Tests
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.127 s - in org.openjdk.asmtools.transform.case8302260Tests
[INFO] Running org.openjdk.asmtools.transform.case7902820Tests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.05 s - in org.openjdk.asmtools.transform.case7902820Tests
[INFO] Running org.openjdk.asmtools.jdis.MainTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.121 s - in org.openjdk.asmtools.jdis.MainTest
[INFO] Running org.openjdk.asmtools.jdis.JdisJasmTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.615 s - in org.openjdk.asmtools.jdis.JdisJasmTest
[INFO] Running org.openjdk.asmtools.SequenceCallsTests
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s - in org.openjdk.asmtools.SequenceCallsTests
[INFO] Running org.openjdk.asmtools.jasm.case7903405.NegativeJasmTests
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.223 s - in org.openjdk.asmtools.jasm.case7903405.NegativeJasmTests
[INFO] Running org.openjdk.asmtools.jasm.MultipleFilesInSingleJasmTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.046 s - in org.openjdk.asmtools.jasm.MultipleFilesInSingleJasmTest
[INFO] Running org.openjdk.asmtools.jasm.case7903558.Tests
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.057 s - in org.openjdk.asmtools.jasm.case7903558.Tests
[INFO] Running org.openjdk.asmtools.jasm.case7903031.TransformationTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.923 s - in org.openjdk.asmtools.jasm.case7903031.TransformationTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 42, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.932 s
[INFO] Finished at: 2024-01-11T11:15:55+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by lkuskov** [comment]
Great. Thank you, changes look good to me. Please integrate.

**Pull request closed without merging**
